spring:
 application:
  name: myapp-client

server:
 port: 9092

eureka:
 client:
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8671/eureka/
 instance:
  hostname: localhost